In [1]:
import numpy as np
import pandas as pd

In [2]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [8]:
df = pd.read_csv("residential-land - residential-land.csv")
df.sample(5)

,property_name,link,society,price,areaWithType,address,floorNumAllowed,noOfOpenSides,possession,nearbyLocations,description,features,rating,property_id
275,Residential land / Plot in Rajendra Park,https://www.99acres.com/residential-land-plot-...,NaN,1 Crore,(167 sq.m.) Plot Area,"Rajendra Park, Gurgaon, Haryana",NaN,NaN,Immediate,"['Palam Vihar Vyapar kendra', 'Chintapurni Man...",Looking for buyer to purchase our land availab...,NaN,"['Environment4 out of 5', 'Safety4 out of 5', ...",H68704236
2002,Residential land / Plot in New Palam Vihar,https://www.99acres.com/residential-land-plot-...,NaN,1.5 Crore,(257 sq.m.) Plot Area,"New Palam Vihar, Gurgaon, Haryana",1 Floors,1.0,Immediate,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",Plot in new palam vihar phase 1 gurgaon,[''],"[['Environment4 out of 5', 'Lifestyle4 out of ...",I69388278
2093,Residential land / Plot in Sector 108 Gurgaon,https://www.99acres.com/residential-land-plot-...,Experion The Westerlies,5.64 Crore,(637 sq.m.) Plot Area,"Sector 108 Gurgaon, Gurgaon, Haryana",NaN,1.0,Immediate,"['WTC Plaza', 'Euro Intl School, Sector- 109',...",Available for sale residential plot near to de...,[['Maintenance Staff']],"[['Environment4 out of 5', 'Lifestyle4.5 out o...",M57291444
463,Residential land / Plot in Sector-33 Sohna,https://www.99acres.com/residential-land-plot-...,Central Park Flower Valley,3.79 Crore,(209 sq.m.) Plot Area,"Sector-33 Sohna, Gurgaon, Haryana",NaN,1.0,Immediate,"['Golf Course Extension Rd', 'Rajiv Chowk - So...","Great deal, east facing on 24m wide road, best...",NaN,NaN,L69572584
60,Residential land / Plot in Sohna,https://www.99acres.com/residential-land-plot-...,NaN,80 Lac,(124 sq.m.) Plot Area,"Sohna, Gurgaon, Haryana",NaN,4.0,Immediate,NaN,"This property is situated in sohna , close to ...",NaN,"['Environment4 out of 5', 'Safety4 out of 5', ...",M69756042

In [9]:
# shape
df.shape

(2422, 14)

In [10]:
# info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2422 entries, 0 to 2421
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    2422 non-null   object
 1   link             2422 non-null   object
 2   society          1328 non-null   object
 3   price            2258 non-null   object
 4   areaWithType     2422 non-null   object
 5   address          2405 non-null   object
 6   floorNumAllowed  367 non-null    object
 7   noOfOpenSides    2178 non-null   float64
 8   possession       1057 non-null   object
 9   nearbyLocations  2148 non-null   object
 10  description      2406 non-null   object
 11  features         1907 non-null   object
 12  rating           2053 non-null   object
 13  property_id      2406 non-null   object
dtypes: float64(1), object(13)
memory usage: 265.0+ KB

In [11]:
# check for duplicates
df.duplicated().sum()

1

In [13]:
df = df.drop_duplicates()

In [14]:
df.shape

(2421, 14)

In [15]:
df.columns

Index(['property_name', 'link', 'society', 'price', 'areaWithType', 'address',
       'floorNumAllowed', 'noOfOpenSides', 'possession', 'nearbyLocations',
       'description', 'features', 'rating', 'property_id'],
      dtype='object')

In [16]:
# Columns to drop -> property_name, link, property_id
df.drop(columns=['link','property_id'], inplace=True)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_13092\3270043815.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns=['link','property_id'], inplace=True)

In [17]:
df.head()

,property_name,society,price,areaWithType,address,floorNumAllowed,noOfOpenSides,possession,nearbyLocations,description,features,rating
0,Residential land / Plot in Sector-33 Sohna,Central Park Flower Valley Mikasa Plots,3.75 Crore,(209 sq.m.) Plot Area,"Sector-33 Sohna, Gurgaon, Haryana",NaN,1.0,NaN,"['Rapid Metro Sector 55-56', 'CBR Cricket Grou...",East facing 24 meter road plot. Very good loca...,"['Feng Shui / Vaastu Compliant', 'Maintenance ...",NaN
1,Residential land / Plot in Sector 93 Gurgaon,ROF Insignia Park,2.23 Crore,(17 sq.m.) Plot Area,"Sector 93, Sector 93 Gurgaon, Gurgaon, Haryana",NaN,1.0,undefined,"['Newtown Square Mall', 'Dwarka Expy', 'Yaduva...",At the maine enterance rof insignia park secto...,NaN,NaN
2,Residential land / Plot in Sector 63 Gurgaon,Adani Brahma Samsara Vilasa,8.75 Crore,(286 sq.m.) Plot Area,"Sector 63 Gurgaon, Gurgaon, Haryana",NaN,2.0,NaN,"['Rapid Metro Station Sector 56', 'Paras Trini...",Park facing plot and open green garden on back...,"['Feng Shui / Vaastu Compliant', 'Maintenance ...",NaN
3,Residential land / Plot in Sector 22 Gurgaon,NaN,90 Lac,(42 sq.m.) Plot Area,"Sector 22 Gurgaon, Gurgaon, Haryana",NaN,2.0,Immediate,"['HUDA Sector 23 Market', 'Palam triangle', 'R...","Huda plot 61 sq. Yards, in sector 22b very uni...",NaN,"['Environment4 out of 5', 'Safety5 out of 5', ..."
4,Residential land / Plot in Block K1 New Palam ...,NaN,1.2 Crore,(167 sq.m.) Plot Area,"Block K1 New Palam Vihar Phase 1, Gurgaon, Har...",4 Floors,2.0,Immediate,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","Lospacious, ready to build plot in block k1 ne...",NaN,NaN

In [18]:
# price
df['price'].value_counts()

price
4.5 Crore           36
1.25 Crore          25
1.8 Crore           23
1.2 Crore           23
4 Crore             22
3 Crore             22
5.5 Crore           21
2.5 Crore           20
5 Crore             20
8 Crore             19
6.5 Crore           18
3.5 Crore           18
7.5 Crore           18
9 Crore             17
5.25 Crore          17
6 Crore             17
Price on Request    16
3.75 Crore          16
15 Lac              15
1.6 Crore           15
7 Crore             15
80 Lac              15
1.1 Crore           14
2 Crore             14
2.2 Crore           14
2.6 Crore           14
1 Crore             13
1.4 Crore           13
60 Lac              13
1.5 Crore           13
3.8 Crore           13
10 Crore            12
2.7 Crore           12
2.1 Crore           12
3.4 Crore           12
4.2 Crore           12
3.1 Crore           12
4.6 Crore           12
1.35 Crore          11
3.25 Crore          11
1.75 Crore          10
90 Lac              10
2.4 Crore           10
1.7 Crore           10
4.8 Crore           10
8.5 Crore           10
2.9 Crore           10
3.6 Crore           10
3.3 Crore           10
1.3 Crore            9
2.3 Crore            9
2.75 Crore           9
2.15 Crore           9
4.25 Crore           9
9.5 Crore            9
1.32 Crore           9
65 Lac               9
4.4 Crore            9
5.1 Crore            9
2.25 Crore           9
8.25 Crore           8
6.25 Crore           8
1.15 Crore           8
1.9 Crore            8
4.75 Crore           8
3.2 Crore            8
3.13 Crore           7
3.7 Crore            7
12.5 Crore           7
8.75 Crore           7
75 Lac               7
30 Lac               7
1.65 Crore           7
18 Lac               7
3.24 Crore           7
3.85 Crore           6
2.58 Crore           6
3.9 Crore            6
6.75 Crore           6
7.25 Crore           6
2.16 Crore           6
13 Crore             6
1.13 Crore           6
1.72 Crore           6
7.5 Lac              6
4.1 Crore            6
10.5 Crore           6
2.55 Crore           6
25 Lac               6
2.8 Crore            6
1.82 Crore           6
5.85 Crore           5
9.2 Crore            5
11 Crore             5
4.3 Crore            5
14 Crore             5
5.7 Crore            5
5.35 Crore           5
3.65 Crore           5
1.85 Crore           5
2.35 Crore           5
50 Lac               5
1.61 Crore           5
17 Lac               5
4.99 Crore           5
1.57 Crore           5
4.47 Crore           5
1.43 Crore           5
2.05 Crore           5
96 Lac               5
2.45 Crore           5
1.24 Crore           5
3.45 Crore           5
7.1 Crore            5
40 Lac               5
3.35 Crore           5
1.96 Crore           5
5.3 Crore            5
9.25 Crore           5
7.2 Crore            5
1.04 Crore           5
3.15 Crore           5
35 Lac               5
15 Crore             4
12 Crore             4
4.45 Crore           4
4.08 Crore           4
2.18 Crore           4
16.5 Crore           4
2.34 Crore           4
2.77 Crore           4
1.92 Crore           4
5.65 Crore           4
16 Lac               4
1.86 Crore           4
1.93 Crore           4
11.25 Crore          4
7.75 Crore           4
10.76 Crore          4
17.5 Crore           4
85 Lac               4
1.95 Crore           4
95 Lac               4
2.09 Crore           4
7.8 Crore            4
2.64 Crore           4
1.17 Crore           4
12 Lac               4
6.15 Crore           4
4.72 Crore           4
1.45 Crore           4
4.24 Crore           4
1.06 Crore           4
1.78 Crore           4
5.4 Crore            4
16 Crore             4
1.98 Crore           4
4.9 Crore            4
2.99 Crore           4
1.47 Crore           4
4.46 Crore           4
1.21 Crore           4
6.6 Crore            4
1.26 Crore           4
63 Lac               4
5.8 Crore            4
21 Crore             4
2.26 Crore           4
12.7 Crore           4
4.79 Crore           4
2.52 Crore           4
1.28 Crore           4
3.48 Crore           4
2.95 Crore           4
2.91 Crore           4
5.6 Crore            4
1.05 Crore           4
5.9 Crore            4
1.33 Crore           4
3.31 Crore           3
2.63 Crore           3
1.38 Crore           3
3.64 Crore           3
4.15 Crore           3
4.48 Crore           3
1.12 Crore           3
6.18 Crore           3
1.27 Crore           3
4.12 Crore           3
1.22 Crore           3
1.88 Crore           3
11.6 Crore           3
3.47 Crore           3
4.38 Crore           3
3.59 Crore           3
11.29 Crore          3
1.97 Crore           3
1.08 Crore           3
9.75 Crore           3
4.7 Crore            3
70 Lac               3
5.55 Crore           3
3.88 Crore           3
3.05 Crore           3
2.47 Crore           3
8.4 Crore            3
5.64 Crore           3
8.28 Crore           3
3.71 Crore           3
11.5 Crore           3
2.38 Crore           3
4.35 Crore           3
11.8 Crore           3
1.73 Crore           3
7.15 Crore           3
2.53 Crore           3
1.81 Crore           3
72 Lac               3
28 Lac               3
3.5 Lac              3
6.11 Crore           3
12.6 Crore           3
5.2 Crore            3
21 Lac               3
2.85 Crore           3
66 Lac               3
1.68 Crore           3
47 Lac               3
1.63 Crore           3
1.67 Crore           3
24 Lac               3
6.45 Crore           3
1.02 Crore           3
2.08 Crore           3
3.04 Crore           3
32 Crore             3
5.05 Crore           3
1.58 Crore           3
3.94 Crore           3
5.26 Crore           3
4.49 Crore           3
10.25 Crore          3
42 Lac               3
6.85 Crore           2
2.98 Crore           2
6.03 Crore           2
56 Lac               2
3.96 Crore           2
31 Lac               2
2.73 Crore           2
26.5 Lac             2
1.01 Crore           2
19 Crore             2
30 Crore             2
5.13 Crore           2
6.3 Crore            2
1.34 Crore           2
7.49 Crore           2
2.24 Crore           2
8 Lac                2
2.83 Crore           2
4.69 Crore           2
6.05 Crore           2
3.29 Crore           2
2.07 Crore           2
2.36 Crore           2
37 Lac               2
4.97 Crore           2
4.64 Crore           2
37.6 Lac             2
4.65 Crore           2
4.55 Crore           2
3.63 Crore           2
1.55 Crore           2
5.01 Crore           2
5.95 Crore           2
3.33 Crore           2
46 Lac               2
54 Lac               2
1.76 Crore           2
87 Lac               2
29 Lac               2
4.85 Crore           2
2.57 Crore           2
2.96 Crore           2
1.44 Crore           2
88 Lac               2
6.53 Crore           2
1.71 Crore           2
3.51 Crore           2
4.01 Crore           2
5.09 Crore           2
5.04 Crore           2
14.5 Crore           2
2.79 Crore           2
7.99 Crore           2
93 Lac               2
5.47 Crore           2
13.5 Crore           2
1.09 Crore           2
2.23 Crore           2
5.92 Crore           2
3.92 Crore           2
2.86 Crore           2
3.01 Crore           2
33 Lac               2
6.65 Crore           2
2.88 Crore           2
2.97 Crore           2
3.67 Crore           2
3.62 Crore           2
2.28 Crore           2
74 Lac               2
7.35 Crore           2
2.87 Crore           2
3.78 Crore           2
55 Lac               2
3.19 Crore           2
28 Crore             2
3.68 Crore           2
89.6 Lac             2
4.87 Crore           2
1.79 Crore           2
2.03 Crore           2
8.8 Crore            2
23.5 Lac             2
2.12 Crore           2
48 Lac               2
11.1 Crore           2
25.5 Crore           2
6.4 Crore            2
6.78 Crore           2
3.52 Crore           2
26 Lac               2
6.1 Crore            2
2.04 Crore           2
3.72 Crore           2
5.21 Crore           2
31 Crore             2
9.1 Crore            2
2.48 Crore           2
20 Crore             2
6.64 Crore           2
5.66 Crore           2
1.48 Crore           2
4.09 Crore           2
8.2 Crore            2
2.92 Crore           2
3.26 Crore           2
4.95 Crore           2
6.9 Crore            2
2.32 Crore           2
4.05 Crore           2
2.13 Crore           2
2.67 Crore           2
1.16 Crore           2
2.51 Crore           2
6.8 Crore            2
45 Lac               2
2.84 Crore           2
1.89 Crore           2
76 Lac               2
82.5 Lac             2
1.46 Crore           2
3.49 Crore           2
4.16 Crore           2
3.89 Crore           2
22.71 Crore          2
8.53 Crore           2
82 Lac               1
2.81 Crore           1
4.34 Crore           1
49.5 Lac             1
7.97 Crore           1
5.76 Crore           1
8.14 Crore           1
5.94 Crore           1
4.13 Crore           1
3.38 Crore           1
12.55 Crore          1
7.96 Crore           1
5.07 Crore           1
2.29 Crore           1
10.55 Crore          1
4.04 Crore           1
13.27 Crore          1
98.01 Lac            1
8.95 Crore           1
3.37 Crore           1
3.22 Crore           1
3.21 Crore           1
76.8 Lac             1
9.05 Crore           1
84.7 Lac             1
2.42 Crore           1
5.52 Crore           1
9.19 Crore           1
1.49 Crore           1
16.25 Crore          1
10.54 Crore          1
13.18 Crore          1
6.06 Crore           1
10.49 Crore          1
6.61 Crore           1
7.42 Crore           1
4.89 Crore           1
2.54 Crore           1
5.98 Crore           1
3.41 Crore           1
12.66 Crore          1
6.19 Crore           1
4.81 Crore           1
6.55 Crore           1
8.3 Crore            1
11.2 Crore           1
1.11 Crore           1
10.5 Lac             1
81 Lac               1
9.4 Crore            1
5.24 Crore           1
66.5 Lac             1
6.09 Crore           1
2.68 Crore           1
2.01 Crore           1
6.28 Crore           1
4.53 Crore           1
11.7 Lac             1
20.3 Crore           1
100 Crore            1
11.3 Lac             1
15.64 Lac            1
1.62 Crore           1
16.52 Lac            1
20.55 Lac            1
17.51 Lac            1
14.53 Lac            1
15.24 Lac            1
16.89 Lac            1
25.87 Lac            1
17.56 Lac            1
3.28 Crore           1
4.14 Crore           1
4.21 Crore           1
18.5 Lac             1
16.2 Lac             1
1.07 Crore           1
9.96 Crore           1
4.88 Crore           1
2.62 Crore           1
13 Lac               1
58 Lac               1
9 Lac                1
75.4 Lac             1
9.7 Crore            1
51 Lac               1
2.49 Crore           1
7.3 Crore            1
13.2 Crore           1
24 Crore             1
5.96 Crore           1
2.06 Crore           1
2.76 Crore           1
5.36 Crore           1
5.33 Crore           1
1.19 Crore           1
37 Crore             1
4.11 Crore           1
6.43 Crore           1
4.37 Crore           1
9.85 Crore           1
19.25 Crore          1
15.5 Crore           1
8.05 Crore           1
5.28 Crore           1
5.81 Crore           1
3.83 Crore           1
14.4 Lac             1
12.93 Crore          1
5.46 Crore           1
4.86 Crore           1
49.75 Lac            1
5.78 Crore           1
12.11 Crore          1
58.45 Lac            1
81.26 Lac            1
7.18 Crore           1
46.5 Lac             1
4.59 Crore           1
22.44 Lac            1
6.52 Crore           1
30.7 Lac             1
22.4 Lac             1
27.2 Lac             1
17.5 Lac             1
26.52 Lac            1
31.5 Lac             1
26.96 Lac            1
27.52 Lac            1
34.2 Lac             1
7.45 Crore           1
11.03 Crore          1
8.46 Crore           1
7.54 Crore           1
5.53 Crore           1
5.51 Crore           1
8.54 Crore           1
8.55 Crore           1
98 Lac               1
64.8 Lac             1
3.17 Crore           1
5.74 Crore           1
5.75 Crore           1
88.5 Lac             1
1.03 Crore           1
95.2 Lac             1
6.12 Crore           1
1.56 Crore           1
1.29 Crore           1
2.21 Crore           1
11.71 Crore          1
4.63 Crore           1
97.75 Lac            1
97.6 Lac             1
10.6 Crore           1
4.02 Crore           1
6.68 Crore           1
4.73 Crore           1
8.45 Crore           1
11.75 Crore          1
12.1 Crore           1
3.06 Crore           1
6.24 Crore           1
6.93 Crore           1
1.95 Lac             1
7.38 Crore           1
6.96 Crore           1
4.03 Crore           1
22 Crore             1
4.39 Crore           1
23 Lac               1
6.34 Crore           1
9.48 Crore           1
6.33 Crore           1
2.11 Crore           1
2.56 Crore           1
7.7 Crore            1
6.27 Crore           1
38.94 Lac            1
1.69 Crore           1
97.5 Lac             1
79.5 Lac             1
8.82 Crore           1
25 Crore             1
7.05 Crore           1
3.77 Crore           1
19.75 Crore          1
1.64 Crore           1
4.26 Crore           1
8.6 Crore            1
14.31 Crore          1
3.79 Crore           1
11.38 Crore          1
29.75 Crore          1
9.11 Crore           1
9.54 Crore           1
10.63 Crore          1
12.45 Crore          1
24.5 Lac             1
6.02 Crore           1
10.8 Crore           1
11.15 Crore          1
62.22 Lac            1
1.39 Crore           1
7.48 Crore           1
6.29 Crore           1
4.44 Crore           1
7.6 Crore            1
6.49 Crore           1
4.57 Crore           1
6.08 Crore           1
8.38 Crore           1
78 Lac               1
6.84 Crore           1
7.03 Crore           1
4.61 Crore           1
7.33 Crore           1
8.66 Crore           1
9.23 Crore           1
11.3 Crore           1
6.16 Crore           1
23.5 Crore           1
2.69 Crore           1
1.74 Crore           1
3.12 Crore           1
68 Lac               1
6.66 Crore           1
5.11 Crore           1
2.82 Crore           1
9.55 Crore           1
10.26 Crore          1
52.5 Lac             1
41 Lac               1
38 Lac               1
12.5 Lac             1
8.5 Lac              1
5.56 Crore           1
9.04 Crore           1
10 Lac               1
34 Crore             1
51.25 Lac            1
3.7 Lac              1
3 Lac                1
22.8 Lac             1
10.79 Crore          1
7 Lac                1
60 Crore             1
39 Lac               1
91.5 Lac             1
30.75 Crore          1
13.75 Crore          1
13.25 Crore          1
3.98 Crore           1
8.1 Crore            1
5.49 Crore           1
10.2 Crore           1
6.7 Crore            1
8.15 Crore           1
4.19 Crore           1
25.51 Crore          1
8.51 Crore           1
8.11 Crore           1
14 Lac               1
10.65 Crore          1
4.76 Crore           1
11.86 Crore          1
9.92 Crore           1
5.27 Crore           1
22 Lac               1
43 Lac               1
1.5 Lac              1
69 Lac               1
6.69 Crore           1
7.65 Crore           1
14.15 Crore          1
4.28 Crore           1
7.63 Crore           1
3.91 Crore           1
2.72 Crore           1
88.9 Lac             1
6.35 Crore           1
6.32 Crore           1
12.2 Crore           1
3.76 Crore           1
4.92 Crore           1
7.09 Crore           1
2.33 Crore           1
6.41 Crore           1
35 Crore             1
68.2 Lac             1
70.4 Lac             1
94.2 Lac             1
98.45 Lac            1
6.2 Crore            1
3.55 Crore           1
3.42 Crore           1
2.74 Crore           1
5.38 Crore           1
18 Crore             1
3.46 Crore           1
19.5 Crore           1
1.84 Crore           1
5.68 Crore           1
3.93 Crore           1
1.36 Crore           1
3.39 Crore           1
1.87 Crore           1
3.34 Crore           1
7.26 Crore           1
92 Lac               1
93.75 Lac            1
1.53 Crore           1
96.05 Lac            1
8.98 Crore           1
7.2 Lac              1
49.92 Lac            1
1.59 Crore           1
5.54 Crore           1
1.42 Crore           1
7.12 Crore           1
67.5 Lac             1
23.51 Lac            1
1.91 Crore           1
36 Lac               1
18.9 Crore           1
2.59 Crore           1
1.37 Crore           1
1.94 Crore           1
3.16 Crore           1
20.28 Lac            1
55.31 Lac            1
55.2 Lac             1
7.9 Crore            1
9.15 Crore           1
2.61 Crore           1
2.19 Crore           1
5.57 Crore           1
6.87 Crore           1
3.43 Crore           1
3.23 Crore           1
33.2 Lac             1
8.7 Crore            1
2.31 Crore           1
93.6 Lac             1
8.13 Crore           1
5.62 Crore           1
8.9 Crore            1
21.28 Crore          1
3.99 Crore           1
1.99 Crore           1
99 Lac               1
32.4 Lac             1
7.4 Crore            1
4.68 Crore           1
95.7 Lac             1
2.27 Crore           1
2.02 Crore           1
65.4 Lac             1
1.23 Crore           1
2.17 Crore           1
5.72 Crore           1
8.85 Crore           1
3.69 Crore           1
12.6 Lac             1
6.95 Crore           1
1.83 Crore           1
9.6 Crore            1
78.1 Lac             1
2.94 Crore           1
4.58 Crore           1
5.34 Crore           1
2.65 Crore           1
4.62 Crore           1
2.39 Crore           1
8.26 Crore           1
9.95 Crore           1
8.01 Crore           1
3.53 Crore           1
Name: count, dtype: int64

In [19]:
df = df[df['price'] != 'Price on Request']

In [20]:
def treat_price(x):
    if type(x) == float:
        return x
    else:
        if x[1] == 'Lac':
            return round(float(x[0])/100,2)
        else:
            return round(float(x[0]),2)

In [21]:
df['price'] = df['price'].str.split(' ').apply(treat_price)

In [22]:
df.head(4)

,property_name,society,price,areaWithType,address,floorNumAllowed,noOfOpenSides,possession,nearbyLocations,description,features,rating
0,Residential land / Plot in Sector-33 Sohna,Central Park Flower Valley Mikasa Plots,3.75,(209 sq.m.) Plot Area,"Sector-33 Sohna, Gurgaon, Haryana",NaN,1.0,NaN,"['Rapid Metro Sector 55-56', 'CBR Cricket Grou...",East facing 24 meter road plot. Very good loca...,"['Feng Shui / Vaastu Compliant', 'Maintenance ...",NaN
1,Residential land / Plot in Sector 93 Gurgaon,ROF Insignia Park,2.23,(17 sq.m.) Plot Area,"Sector 93, Sector 93 Gurgaon, Gurgaon, Haryana",NaN,1.0,undefined,"['Newtown Square Mall', 'Dwarka Expy', 'Yaduva...",At the maine enterance rof insignia park secto...,NaN,NaN
2,Residential land / Plot in Sector 63 Gurgaon,Adani Brahma Samsara Vilasa,8.75,(286 sq.m.) Plot Area,"Sector 63 Gurgaon, Gurgaon, Haryana",NaN,2.0,NaN,"['Rapid Metro Station Sector 56', 'Paras Trini...",Park facing plot and open green garden on back...,"['Feng Shui / Vaastu Compliant', 'Maintenance ...",NaN
3,Residential land / Plot in Sector 22 Gurgaon,NaN,0.90,(42 sq.m.) Plot Area,"Sector 22 Gurgaon, Gurgaon, Haryana",NaN,2.0,Immediate,"['HUDA Sector 23 Market', 'Palam triangle', 'R...","Huda plot 61 sq. Yards, in sector 22b very uni...",NaN,"['Environment4 out of 5', 'Safety5 out of 5', ..."

In [24]:
df["noOfOpenSides"].value_counts()

noOfOpenSides
1.0    1207
2.0     799
3.0     123
4.0      34
Name: count, dtype: int64

In [26]:
df["noOfOpenSides"].isnull().sum()

242